version: '3.8'
services:
  mongo_db:
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=your_password  # Replace with your MongoDB root password
    volumes:
      - ./path-to-your-json-directory:/docker-entrypoint-initdb.d/
    restart: unless-stopped

  nest_app_1:
    build:
      context: .
      dockerfile: ./path-to-your-nestjs-app/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://root:your_password@mongo_db:27017/your_database  # Adjust URI and database name
    depends_on:
      - mongo_db
    restart: unless-stopped

  nest_app_2:
    build:
      context: .
      dockerfile: ./path-to-your-nestjs-app/Dockerfile  # Replace with correct path
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://root:your_password@mongo_db:27017/your_database
    depends_on:
      - mongo_db
    restart: unless-stopped

  react_app:
    build:
      context: .
      dockerfile: ./path-to-your-reactjs-app/Dockerfile  # Replace with correct path
    ports:
      - "4000:4000"
    depends_on:
      - mongo_db
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    volumes:
      - ./portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
