version: '3.8'
services:
  mongo_db:
    image: mongo:4.4
    ports:
      - "${MONGO_PORT_EXTERNAL}:${MONGO_PORT_INTERNAL}"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - ./mongodb-init:/docker-entrypoint-initdb.d/  # MongoDB init scripts
    restart: unless-stopped

  nest_app_1:
    build:
      context: .
      dockerfile: ./nest-app-1/Dockerfile
    ports:
      - "${NEST_APP_1_PORT_EXTERNAL}:${NEST_APP_1_PORT_INTERNAL}"
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo_db
    restart: unless-stopped

  nest_app_2:
    build:
      context: .
      dockerfile: ./nest-app-2/Dockerfile
    ports:
      - "${NEST_APP_2_PORT_EXTERNAL}:${NEST_APP_2_PORT_INTERNAL}"
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo_db
    restart: unless-stopped

  react_app:
    build:
      context: .
      dockerfile: ./react-app/Dockerfile
    ports:
      - "${REACT_APP_PORT_EXTERNAL}:${REACT_APP_PORT_INTERNAL}"
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    depends_on:
      - mongo_db
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    volumes:
      - ./portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${PORTAINER_PORT_EXTERNAL}:${PORTAINER_PORT_INTERNAL}"
    restart: unless-stopped
